### ISSUE TITLE
MS Office 2013 leads to segfault in marco compositor

### ISSUE THREAD

**Issue by katakombi** [dolmades/dolmades-cli#11]
On Startup marco segfaults:

```
[40156.404470] marco[6391]: segfault at 555f8970cd3e ip 0000555f868f7981 sp 00007fff196c1960 error 6 in marco[555f868de000+8f000]
```

Workaround: start up a console and restart marco

**Comment by katakombi** [comment]
GFX card Intel Ivy Bridge, happens with both the intel and the modesetting drivers

**Comment by serious-steve** [comment]
okay, it has to do with compositing. Viable workaround for now: disable compositing
